### ISSUE TITLE
Current optimum outside 90% confidence intervals

### ISSUE THREAD

**Issue by hans-ekbrand** [kiudee/chess-tuning-tools#102]
* Chess Tuning Tools version: 0.5.1
* Python version: 3.8.5
* Operating System: Debian unstable

### Description

```
2020-09-21 09:16:20,072 INFO     Starting iteration 125
2020-09-21 09:16:20,519 INFO     Current optimum:
{'CPuctBase': 36.2}
2020-09-21 09:16:20,519 INFO     Estimated value: -0.32668792113088846
2020-09-21 09:16:20,683 INFO     90.0% confidence intervals:
Parameter  Lower bound  Upper bound
-----------------------------------
CPuctBase         15.0         36.0

2020-09-21 09:16:20,683 WARNING  Plotting for only 1 parameter is not supported yet.
```
36.2 is the upper bound of the testing range

```
    "parameter_ranges": {
        "CPuctBase": "Real(5, 36.2)"
    },
```

**Comment by hans-ekbrand** [comment]
Here are the Current optima over time, looks a bit weird too.

```
grep -C 1 Current log.txt | grep CPuct
{'CPuctBase': 23.23377009407588}
{'CPuctBase': 22.519968942001153}
{'CPuctBase': 24.687279704195866}
{'CPuctBase': 24.67759673137418}
{'CPuctBase': 24.576143588835862}
{'CPuctBase': 24.31609314021852}
{'CPuctBase': 25.052984947407186}
{'CPuctBase': 23.474685637885045}
{'CPuctBase': 24.013884906277642}
{'CPuctBase': 24.444464331611744}
{'CPuctBase': 25.4116541127404}
{'CPuctBase': 29.69032385173715}
{'CPuctBase': 29.5382173374221}
{'CPuctBase': 32.36441695181038}
{'CPuctBase': 34.81581947173477}
{'CPuctBase': 34.47685309324521}
{'CPuctBase': 22.775658463743746}
{'CPuctBase': 22.354366185161407}
{'CPuctBase': 21.766092688944827}
{'CPuctBase': 36.2}
{'CPuctBase': 36.2}
{'CPuctBase': 36.2}
{'CPuctBase': 35.928555324069166}
{'CPuctBase': 36.2}
{'CPuctBase': 36.2}
```

**Comment by hans-ekbrand** [comment]
I use 32 rounds per iteration, is this too noise data for 32 rounds?

**Comment by kiudee** [comment]
Yes, that can happen - especially when the distribution of optima is skewed in one direction.
To give a bit more context on how the confidence intervals are computed: It samples optimization landscapes from the model which are consistent with the observed data. For each landscape it will determine the optimum and record it. Afterwards it will compute the highest density intervals for each parameter.

For `CPuctBase` it is plausible that it prefers the maximum value of the range. Usually you would set it to values in the range 1000 - 30000. During our experiments with tuning CPuctBase we also observed that high values tended to be stronger, since the tuner was able to use more aggressive CPuctFactor values.

**Comment by hans-ekbrand** [comment]
OK, then I'll close the issue!
