### ISSUE TITLE
Add vast.ai scripts for tuning on remote GPUs

### ISSUE THREAD

**Issue by kiudee** [kiudee/chess-tuning-tools#46]
Many are using rental GPUs to tune Lc0 or other GPU engines. Since quite a few dependencies need to be set up, it would be useful to have example scripts.

#33 is a pull request in that direction.

**Comment by AlexisOlson** [comment]
It may be worth noting in [/examples/vastai/](https://github.com/kiudee/chess-tuning-tools/tree/vastai/examples/vastai) README that `onstart.sh` can be inserted into the Instance Configuration instead of manually copying and running it.

![image](https://user-images.githubusercontent.com/10537957/89936387-2d24e400-dbd9-11ea-9a4b-8f7bd049030c.png)

**Comment by kiudee** [comment]
Good idea.

By the way - do you think that the tuning script should be automatically started the first time after setup?
It could be useful to just do the setup and then the user can do benchmarks/calibration before running onstart.sh again to start the script.

**Comment by AlexisOlson** [comment]
I don't think you necessarily want to start the actual tune automatically but installing the components needed to run the tune does make sense. Maybe run the tuning only if it's been run manually at least once.
